### PR TITLE
Sundials 6.0 support

### PR DESCRIPTION
**Pull request by kwabenantim**
## Description
These changes add support for [Sundials 6.0.0](https://computing.llnl.gov/projects/sundials/release-history) which requires a newly introduced [SUNContext](https://sundials.readthedocs.io/en/latest/sundials/SUNContext_link.html) object.

## Motivation and Context
- These changes are related to Chaste ticket [#3084](https://chaste.cs.ox.ac.uk/trac/ticket/3084) for Sundials 6.0.0 support.
- Preprocessor directives were added to boilerplate code and reference models to account for the changes in Sundials library function calls.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Documentation checklist

- [ ] I have updated all documentation in the code where necessary.
- [ ] I have checked spelling in all (new) comments and documentation.
- [ ] I have added a note to RELEASE.md if relevant (new feature, breaking change, or notable bug fix).
- [ ] I have updated version & citation.txt & citation.cff version.

## Testing
- [ ] Testing is done automatically and codecov shows test coverage
- [ ] This cannot be tested automatically 
- [x] This can be tested automatically, but requires Sundials 6.0.0 to be installed. It has been tested manually in a [chaste-docker](https://github.com/Chaste/chaste-docker) container. The recommended tests all passed:
    - chaste-codegen pytest
    - Chaste test pack Codegen
    - Chaste test pack project_ApPredict

### CODE REVIEW

**Review by MauriceHendrix — CHANGES_REQUESTED** [review]
Have you managed to use this version together with chaste tests?

Those fails you are seeying with the python 3.8 test are because of some python 3.6 specific reference files (subtle format change due to sympy versions).
The files are the `.cpp_alt` files in `.../data/tests/chaste_reference_models/..`

You can either regenerate them using python3.6, or otherwise just manaually change them

**Comment by kwabenantim** [comment]
> Have you managed to use this version together with chaste tests?
> 
> Those fails you are seeying with the python 3.6 test are because of some python 3.6 specific reference files (subtle format change due to sympy versions). The files are the `.cpp_alt` files in `.../data/tests/chaste_reference_models/..`
> 
> You can either regenerate them using python3.6, or otherwise just manaually change them

Thank you, @MauriceHendrix. I'll modify those files and test again with python 3.6.

**Review by MauriceHendrix — APPROVED** [review]
I'm assuming this is backwards compatible? I.e. this would still work with teh current release of chaste?

**Comment by kwabenantim** [comment]
> I'm assuming this is backwards compatible? I.e. this would still work with teh current release of chaste?

Yes @MauriceHendrix, this also works for the current release of Chaste, for Sundials versions before 6.0.
For Sundials 6.0+, there is also a [Chaste pull request](https://github.com/Chaste/Chaste/pull/17) in progress.

**Pull request merged**
