### PR TITLE
better support for secondary trig functions

### PR DESCRIPTION
**Pull request by MauriceHendrix**
## Description

Better support for secondry trig functions

## Motivation and Context

Although not really used in the existing models tested callmlmanip has gained support for these functions so we might as well support them too.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Documentation checklist

- [X] I have updated all documentation in the code where necessary.
- [ ] I have checked spelling in all (new) comments and documentation.
- [ ] I have added a note to RELEASE.md if relevant (new feature, breaking change, or notable bug fix).

## Testing
- [X] Testing is done automatically and codecov shows test coverage
- [ ] This cannot be tested automatically

### CODE REVIEW

**Review by MichaelClerx — APPROVED** [review]

**Review by mirams — COMMENTED** [review]
Don't quite get these, it seems to be saying "sec is another name for cos" etc., but sec = 1/cos ?

**Comment by MichaelClerx** [comment]
The code that handles them is in cellmlmanip https://github.com/ModellingWebLab/cellmlmanip/blob/master/cellmlmanip/printer.py#L213-L237

**Comment by MichaelClerx** [comment]
Just noticed that I didn't add tests (or think about) brackets for the 1/x cases - could go wrong if the rules for functions are being used?

**Comment by mirams** [comment]
OK, maybe nicer to rename it from `extra names` to `reciprocals`?

**Comment by MauriceHendrix** [comment]
> OK, maybe nicer to rename it from `extra names` to `reciprocals`? Or such like

Actually that's up to cellmlmanip since it's inherited I can't go changing those names :)

**Comment by mirams** [comment]
> Just noticed that I didn't add tests (or think about) brackets for the 1/x cases - could go wrong if the rules for functions are being used?

Yeah, worth sticking some extra brackets and tests in there!

**Comment by MauriceHendrix** [comment]
> Just noticed that I didn't add tests (or think about) brackets for the 1/x cases - could go wrong if the rules for functions are being used?

Following C++ code 1st one gets from 1/sec(x), 2nd one I've stuck brackets in
```
float x = 12.12;
std::cout << 1 / 1 / cos(x)<<std::endl;
std::cout << 1 / (1 / cos(x))<<std::endl;

```

```
1.10862
0.90202
```

sorry for not noticing this when reviewing originally

**Pull request merged**
